version: "3.9"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://localhost:11434/health" ]
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 5

volumes:
  ollama_data:
    name: ollama_data
