version: "3.9"

services:
  api:
    build: .
    environment:
      OLLAMA_BASE_URL: http://localhost:11434
      OLLAMA_MODEL: phi3:mini
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"

